//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace externalPrcatice1
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueTbl
    {
        public int Id { get; set; }
        public Nullable<int> BookID { get; set; }
        public string IssuedTo { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual BookTbl BookTbl { get; set; }
    }
}
